#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <winsock2.h>
#include <cstdlib>
#include <ctime>

std::string readFile(const std::string& fileName) {
    std::ifstream file(fileName);
    if (!file.is_open()) return "";
    std::stringstream buffer;
    buffer << file.rdbuf();
    return buffer.str();
}

int main() {
    WSADATA wsaData;
    if (WSAStartup(MAKEWORD(2, 2), &wsaData) != 0) {
        std::cerr << "Failed to initialize Winsock." << std::endl;
        return 1;
    }

    SOCKET serverSocket = socket(AF_INET, SOCK_STREAM, 0);
    sockaddr_in serverAddr{};
    serverAddr.sin_family = AF_INET;
    serverAddr.sin_addr.s_addr = INADDR_ANY;
    serverAddr.sin_port = htons(8080);

    bind(serverSocket, (struct sockaddr*)&serverAddr, sizeof(serverAddr));
    listen(serverSocket, 5);

    std::cout << "C++ Web Server running at http://localhost:8080" << std::endl;
    srand(time(0));

    while (true) {
        SOCKET clientSocket = accept(serverSocket, NULL, NULL);
        if (clientSocket == INVALID_SOCKET) continue;

        char buffer[1024] = { 0 };
        recv(clientSocket, buffer, sizeof(buffer), 0);
        std::string request(buffer);

        std::string response;
        if (request.find("GET /style.css") != std::string::npos) {
            std::string content = readFile("style.css");
            response = "HTTP/1.1 200 OK\r\nContent-Type: text/css\r\n\r\n" + content;
        }
        else if (request.find("GET /api/data") != std::string::npos) {
            // Simulated live dynamic sensor metrics generated by C++
            int power = 250 + (rand() % 100);
            int battery = 70 + (rand() % 28);
            std::string json = "{\"power\":" + std::to_string(power) +
                ",\"battery\":" + std::to_string(battery) +
                ",\"status\":\"Optimal\"}";
            response = "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n" + json;
        }
        else {
            std::string content = readFile("index.html");
            response = "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n" + content;
        }

        send(clientSocket, response.c_str(), response.length(), 0);
        closesocket(clientSocket);
    }

    WSACleanup();
    return 0;
}